// IS SIGNED IN
export const ISSIGNEDIN_SUCCESS = 'ISSIGNEDIN_SUCCESS'
export const ISSIGNEDIN_ERROR = 'ISSIGNEDIN_ERROR'
// SIGN UP
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
// SIGN IN
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'
export const SIGNIN_GOOGLE_SUCCESS = 'SIGNIN_GOOGLE_SUCCESS'
export const SIGNIN_GOOGLE_ERROR = 'SIGNIN_GOOGLE_ERROR'
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
// SIGN OUT
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR'
// RESET PASSWORD
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_ERROR = 'RESET_ERROR'